config/routes.rb
Rails.application.routes.draw do

  resources :golf_courses do
    resources :tee_ratings
  end
  resources :tee_ratings do
    resources :scores
  end

  resources :tee_ratings
  resources :scores

  devise_for :users
  resources :users do
    resources :friendships
  end

  root 'welcome#index'

  devise_scope :user do
    get 'login', to: "devise/sessions#new", as: :login
    get 'logout', to: "devise/sessions#destroy", as: :logout
    get 'register', to: "devise/registrations#new", as: :register
  end

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, :class_name => "User"
  validates :user, uniqueness: {:scope => :friend}
end

app/models/golf_course.rb
class GolfCourse < ActiveRecord::Base
  validates :name, presence: true
  validates :location, presence: true
  has_many :tee_ratings
  has_many :scores, through: :tee_ratings


  def self.search(location)
    golf_courses_info = []
    golf_courses = Yelp.client.search(location, { category_filter: 'golf', sort: 2, limit: 20, term: 'golf' })
    golf_courses = golf_courses.as_json
    golf_courses["hash"]["businesses"].each do |business|
      golf_courses_info << { name: business["name"], location: business["location"]["display_address"], phone: business["display_phone"], rating: business["rating"] }
      # GolfCourse.search(name: business["name"], location: business["location"]["display_address"].to_s)
    end
    golf_courses_info
  end
end

app/models/score.rb
class Score < ActiveRecord::Base
  validates :score, presence: true
  validates :date, presence: true
  validates :user, presence: true
  validates :tee_rating, presence: true

  belongs_to :tee_rating
  belongs_to :user

  accepts_nested_attributes_for :tee_rating
end

app/models/tee_rating.rb
class TeeRating< ActiveRecord::Base
  validates :golf_course,
    uniqueness: { scope: :color }
  validates :course_rating, presence: true
  validates :slope_rating, presence: true
  validates :color, presence: true

  has_many :scores
  belongs_to :golf_course

  accepts_nested_attributes_for :golf_course

  def self.colors
    ["Red", "White", "Blue"]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user
  has_many :scores


  mount_uploader :profile_photo, ProfilePhotoUploader

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip_code, presence: true

  def self.search(query)
    where("first_name ilike :q or last_name ilike :q or first_name ilike :q", q: "%#{query}%")
  end

  def name
    first_name.capitalize + " " + last_name.capitalize
  end

  def differential
    differential = []
    recent_scores = scores.order(date: :desc)
    recent_scores.each do |score|
      differential << (((score.score - score.tee_rating.course_rating) * 113) / score.tee_rating.slope_rating)
    end
    differential.first(20).sort
  end

  def handicap
    differentials = differential
    if differentials.count < 16
      divisors = (differentials.count - 3) / 2
    else
      divisors = differentials.count - 10
    end
    sum = differentials.first(divisors).inject{ |sum, x| sum + x }
    ((sum / divisors) * 0.96).round(1)
  end

  def friends_with?(user)
    friendships.find_by(friend: user) || friendships.find_by(user: user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:first_name, :last_name, :city, :state, :zip_code, :profile_photo]
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def index
    @friendship = Friendship.all

  end

  def create
    @friendship = current_user.friendships.build(:friend_id => params[:user_id])
    if @friendship.save
      flash[:notice] = "Added Friend"
      redirect_to users_path
    else
      flash[:error] = "Unable to add friend"
      redirect_to users_path
    end
  end

  def destroy
    @friendship = current_user.friendships.find_by(user_id: params[:user_id])
    @friendship.destroy
    flash[:notice] = "Removed Friend"
    redirect_to current_user
  end
end

app/controllers/golf_courses_controller.rb
class GolfCoursesController < ApplicationController
  before_filter :authenticate_user!

  def index
    @golf_courses = GolfCourse.search(params[:golf_course_search]) if params[:golf_course_search]
    # GolfCourse.search(params[:golf_course_search]) if params[:golf_course_search]
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_filter :authenticate_user!

  def index
    @scores = Score.all
  end

  def show
    @score = Score.find(params[:id])
  end

  def new
    @score = Score.new
    @golf_course = GolfCourse.new
    @tee_rating = TeeRating.new
  end

  def create
    @score = Score.new(score_params)
    @golf_course = GolfCourse.find_or_create_by(golf_course_params)
    @tee_rating = TeeRating.find_or_create_by(tee_rating_params.merge(golf_course: @golf_course))
    @score.tee_rating = @tee_rating
    if @score.save
      flash[:notice] = 'Score was successfully submitted!'
      redirect_to user_path(current_user)
    else
      flash[:notice] = 'Please fill in required information'
      render :new
    end
  end

  private
  def score_params
    params.require(:score).permit(:score, :date).merge(user: current_user)
  end

  def golf_course_params
    params[:score].require(:golf_course).permit(:name, :location)
  end

  def tee_rating_params
    params[:score].require(:tee_rating).permit(:color, :course_rating, :slope_rating)
  end
end

app/controllers/tee_ratings_controller.rb
class TeeRatingsController < ApplicationController
  def index
    @tee_ratings = TeeRating.all
  end

  def show
    @tee_rating = TeeRating.find(params[:id])
    @score = Score.new
  end

  def new
    @golf_course = GolfCourse.find(params[:golf_course_id])
    @tee_rating = TeeRating.new
  end

  def create
    binding.pry
      @tee_rating = TeeRating.new(tee_rating_params)
      if @tee_rating.save
        flash[:notice] = 'Score was successfully added!'
        # need to redirect to scores page
        redirect_to golf_course_path(@golf_course)
      else
        flash[:notice] = 'Please fill in required information'
        render :new
      end
  end

  private
  def tee_rating_params
    params.require(:tee_rating).permit(:color, :course_rating, :slope_rating)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @scores = @user.scores
    render layout: "profile"
  end

  def index
    if params[:search]
      @users = User.search(params[:search])
    else
      @users = User.all
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    render layout: "welcome"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/golf_courses_helper.rb
module GolfCoursesHelper
end

app/views/friendships/index.html.erb
<div id="users">
  <% @users.each do |user| %>
    <%= link_to user.name, user_path(user) %>
    <%= link_to "Add Friend", user_path(user), class: "button tiny round" %>
  <% end %>
</div>

app/views/golf_courses/index.html.erb
<div class="golf_course-bg">
    <div class= "golfcourse">
      <%= form_tag golf_courses_path, method: :get do %>
      <%= text_field_tag :golf_course_search, params[:search], placeholder: "Search Nearby Golf Courses" %>
      <%= submit_tag "Submit", class: "button round tiny", :title => nil%>
      <% end %>
      <div class="row">
        <div class="large-12 columns">
          <table class="transparent shape">
            <% unless @golf_courses.nil? %>
              <% @golf_courses.each do |gc| %>
                <ul>
                  <li>
                    <%= "#{gc[:name]} - #{gc[:location][0]}, #{gc[:location][1]}, #{gc[:location][2]}" %>
                  </li>
                  <ul>
                    <%= "Phone Number: #{gc[:phone]} // Rating: #{gc[:rating]}"  %>
                  </ul>
                </ul>
              <% end %>
            <% end %>
          </table>
        </div>
      </div>
    </div>
</div>

app/views/layouts/_main_navbar.html.erb
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><strong><a href="/">HandiTrack</a></strong></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">

    <ul class="left">
      <li class="active">
      <% if !user_signed_in? %>
        <%= link_to "Sign up", new_user_registration_path %>
        <% end %>
      </li>

      <% if !user_signed_in? %>
        <li class ="active"><a href="/users/sign_in">Sign In</a></li>
      <% end %>

        <li class="active">
        <%= link_to "Submit a Score", new_score_path %>
      </li>

      <li>
        <%= form_tag(users_path, :method => "get", id: "search-form") do %>
        <ul>
          <li>
            <%= text_field_tag :search, params[:search], placeholder: "Search Friends", class: "radius", name: 'search' %>
          </li>
          <li>
            <%= submit_tag "Search", class: "button radius", :title => nil %>
          </li>
        </ul>
        <% end %>
      </li>
    </ul>
    <ul class="right">
      <li class="active border">
        <%= link_to "Golf Courses", golf_courses_path %>
      </li>
      <% if user_signed_in? %>
        <li class="active border">

      <%= link_to user_path(current_user) do %>
        <i class="fa fa-user"></i>
        <% end %>
        </li>
        <li class="active">
          <%= link_to "Sign out", logout_path %>
        </li>
    </ul>
    <% end %>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "HandiTrak" %></title>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <link href='http://fonts.googleapis.com/css?family=Signika:400,700' rel='stylesheet' type='text/css'>
  </head>

<body>
  <%= render 'layouts/main_navbar'%>


<% if flash.any? %>
  <div class="alert-box secondary">
    <div class="container">
      <%= flash[:notice] %>
    </div>
  </div>
<% end %>

<div class="row ">
  <div class="small-12 columns">
    <%= yield %>
  </div>
</div>

  </body>
</html>

app/views/layouts/golf_courses.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "HandiTrak" %></title>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <link href='http://fonts.googleapis.com/css?family=Signika:400,700' rel='stylesheet' type='text/css'>
  </head>

<body>
  <%= render 'layouts/main_navbar'%>


<% if flash.any? %>
  <div class="alert-box secondary">
    <div class="container">
      <%= flash[:notice] %>
    </div>
  </div>
<% end %>

<%= yield %>

  </body>
</html>

app/views/layouts/profile.html.erb
<!-- credit codepen.io-->
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "HandiTrak" %></title>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <link href='http://fonts.googleapis.com/css?family=Signika:400,700' rel='stylesheet' type='text/css'>
  </head>

<body>

  <%= render 'layouts/main_navbar'%>

<div id="animation">
  <div class="ground">
      <div class="hill"></div>
      <div class="hill"></div>
      <div class="hill"></div>
      <div class="hill"></div>
  </div>
  <div class="green"></div>
  <div class="hole"></div>
  <div class="pole"></div>
  <div class="flag"></div>
  <div class="shot">
    <div class="ball">
      <div></div>
    </div>
    <div class="shadow"></div>
  </div>
</div>



<% if flash.any? %>
  <div class="alert-box secondary">
    <div class="container">
      <%= flash[:notice] %>
    </div>
  </div>
<% end %>

<div class="row ">
  <div class="small-12 columns">
  <%= yield %>
  </div>
</div>

  </body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "HandiTrak" %></title>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <link href='http://fonts.googleapis.com/css?family=Signika:400,700' rel='stylesheet' type='text/css'>
  </head>

<body>
  <%= render 'layouts/main_navbar'%>


<% if flash.any? %>
  <div class="alert-box secondary">
    <div class="container">
      <%= flash[:notice] %>
    </div>
  </div>
<% end %>

<%= yield %>

  </body>
</html>

app/views/scores/new.html.erb
  <h2> Add A New Score </h2>

  <%= form_for @score do |f| %>

  <% if @score.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@score.errors.count, "error") %> prohibited this score from being submitted:</h2>

      <ul>
      <% @score.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.fields_for @golf_course do |golf_course| %>
    <div>
      <%= golf_course.label :name %><br />
      <%= golf_course.text_field :name %>
    </div>

    <div>
      <%= golf_course.label :location %><br />
      <%= golf_course.text_field :location %>
    </div>
  <% end %>

  <%= f.fields_for @tee_rating do |tee_rating| %>
    <div>
      <%= tee_rating.label :color %><br />
      <%= tee_rating.collection_select :color, TeeRating.colors, :to_s, :to_s %>
    </div>

    <div>
      <%= tee_rating.label :course_rating %><br />
      <%= tee_rating.text_field :course_rating %>
    </div>

    <div>
      <%= tee_rating.label :slope_rating %><br />
      <%= tee_rating.text_field :slope_rating %>
    </div>
  <% end %>

 <div>
    <%= f.label :score %><br />
    <%= f.text_field :score %>
  </div>

  <div>
    <%= f.label :date %><br />
    <%= f.text_field :date %>
  </div>

  <div><%= f.submit "Add Score", class: "button active" %></div>
<% end %>

<%= link_to "Back", :back %>

app/views/tee_ratings/new.html.erb
  <h2> Add A New Score </h2>

  <%= form_for @tee_rating do |f| %>
  <% if @tee_rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tee_rating.errors.count, "error") %> prohibited this tee_rating from being submitted:</h2>

      <ul>
      <% @tee_rating.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>

    <div>
    <%= f.label :course_rating %><br />
    <%= f.text_field :course_rating %>
  </div>

  <div>
    <%= f.label :slope_rating %><br />
    <%= f.text_field :slope_rating %>
  </div>

 <div>
    <%= f.label :score %><br />
    <%= f.text_field :score %>
  </div>

  <div><%= f.submit "Add Score", class: "button active" %></div>
<% end %>

<%= link_to "Back", :back %>

app/views/users/index.html.erb
<% "Friend List" %>

<div id="users">
  <% @users.each do |user| %>
    <div class="user_list">
      <div class="user">
        <%= link_to user.name, user_path(user) %>
      </div>
      <div class="user_add_button">
        <%= link_to "Add Friend", user_friendships_path(user), class: "button tiny round" %>
      </div>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="shape panel large-12 columns">
    <div class="row">
      <div class="large-3 columns">
        <img src="<%= @user.profile_photo %>" alt="profile photos" class="profile"/>
      </div>
      <div class="large-3 columns">
        <h2><%= @user.name%></h2>
        <h5><%= "#{@user.city.titleize}, #{@user.state.capitalize} #{@user.zip_code}" %></h5>

        <% if user_signed_in? && current_user == @user %>
          <h6><%= link_to 'Edit Profile', edit_user_registration_path, class: "button tiny round" %></h6>
        <% end %>
        <% if user_signed_in? && current_user != @user && current_user.friends_with?(@user) %>
          <%= button_to "Delete Friend", user_friendship_path(current_user, @user), :confirm => "Are you sure you want to delete this attachment?", method: :delete, class: "button tiny round" %>
        <% elsif user_signed_in? && current_user != @user %>
          <%= button_to "Add Friend", user_friendships_path(@user), class: "button tiny round" %>
        <% end %>
      </div>
      <div class="large-6 columns">
        <h3> Current Handicap: <%= @scores.count < 5 ? 'Requires a minimum of 5 scores' : @user.handicap %></h3>
      </div>
    </div> <!--  close row -->
  </div>
</div>
<div class="row">
  <div class="large-12 columns">
    <table class="transparent shape">
      <tr>
        <th>Golf Course</th>
        <th>Score</th>
        <th>Date</th>
      </tr>
        <% recent_scores = @scores.sort_by { |x| x.date }.reverse %>
        <% recent_scores.each do |score| %>
          <tr>
            <td><%= score.tee_rating.golf_course.name %> </td>
            <td><%= score.score %></td>
            <td><%= score.date %></td>
          </tr>
        <% end %>
    </table>
  </div>
</div>
<div class="row">
  <div class="large-12 columns">
    <div class="large-6 columns">
      <%= link_to "Following", "#", class: "button dropdown round small", data: { dropdown: "following" } %>
        <ul id="following" data-dropdown-content class="f-dropdown" aria-hidden="true" tabindex="-1">
          <% @user.friendships.each do |friendship| %>
            <li>
              <%= link_to friendship.friend.name, user_path(friendship.friend_id) %>
            </li>
          <% end %>
        </ul>

      <%= link_to "Followers", "#", class: "button dropdown round small", data: { dropdown: "followers" } %>
        <ul id="followers" data-dropdown-content class="f-dropdown" aria-hidden="true" tabindex="-1">
          <% @user.inverse_friends.each do |user| %>
            <li>
              <%= link_to user.name, user_path(user) %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

<h6><%= link_to "Find Friends", users_path %></h6>
</div>

app/views/welcome/index.html.erb
<div class="welcome-bg">
  <div class="intro-container">
    <div class = "intro">
      <h3><strong>Handitrak</strong> is your personal online caddy. Track your handicap, improve your game, and get paid for green fees.</h3>
      <%= image_tag 'golf_icon.png', class: "started" %>
      <h3>Get Started Today!</h3>
    </div>
  </div>
</div>